baseURL = "https://awllee.github.io/blogdown-test/"
languageCode = "en-us"
title = "BT"

theme = "hugo-ivy"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
[[menu.main]]
    name = "Notes"
    url = "/note/"
    weight = 2
[[menu.main]]
    name = "Slides"
    url = "/slides/"
    weight = 2.5
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 3

[params]
    description = "Blogdown Test"
    footer = "&copy; [Anthony Lee](https://sites.google.com/view/anthonylee) 2019 | [Github](https://github.com/awllee)"
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "github"
    GithubEdit = "https://github.com/awllee/blogdown-test/edit/master/content/"
